name: Solar System Workflow
on:
    workflow_dispatch: 
    push:
        branches: 
            - main
            - 'feature/*'
env:
  MONGO_URI: 'mongodb://localhost:27017/superData'
  MONGO_USERNAME: ${{ vars.MONGODB_SERVICE_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGODB_SERVICE_PASSWORD }}
jobs:
    unit-testing:
        name: Unit Testing
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            ports:
              - 27017:27017
        strategy:
          matrix:
            nodejs_version: [18]
            os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Setup NodeJs (v${{ matrix.nodejs_version }})
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.nodejs_version }}
            - name: Cache npm Modules
              uses: actions/cache@v4
              with:
                path: node_modules
                key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
            - name: Install Dependencies
              run: npm install
            - name: Unit Testing
              id: unit-testing-step
              run: npm test
            - name: Archive Test Result
              if: always()
              uses: actions/upload-artifact@v4.6.2
              with:
                name: Mocha-Test-Result-${{ matrix.os }}-${{ matrix.nodejs_version }}
                path: test-results.xml
    code-coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        env:
          MONGO_URI: 'mongodb://mongodb:27017/superData'
        container:
          image: node:18
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            options:
              --name mongodb
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Cache npm Modules
              uses: actions/cache@v4
              with:
                path: node_modules
                key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
            - name: Install Dependencies
              run: npm install
            - name: Check Code Coverage
              continue-on-error: true
              run: npm run coverage
            - name: Archive Test Result
              uses: actions/upload-artifact@v4.6.2
              with:
                name: code-coverage-result
                path: coverage
                retention-days: 5
    build-push-image:
        name: Build & Push to GHCR
        needs: [unit-testing, code-coverage]
        runs-on: ubuntu-latest
        permissions: 
          packages: write
        env:
          MONGO_URI: 'mongodb://mongodb:27017/superData'
        services:
          mongodb:
            image: siddharth67/mongo-db:non-prod
            options:
              --name mongodb
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
          - name: Build Image
            uses: docker/build-push-action@v4
            with:
              context: .
              push: false
              tags: ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}
          - name: Fetch Github Docker Network
            run: echo "GITHUB_NETWORK=$(docker network ls --filter name=github --format "{{.Name}}")" >> $GITHUB_ENV
          - name: Test Image
            run: |
              docker run --name solar-system-app -d \
                --network ${{ env.GITHUB_NETWORK }} \
                -p 3000:3000 \
                -e MONGO_URI=${{ env.MONGO_URI }} \
                -e MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
                -e MONGO_PASSWORD=${{ env.MONGO_PASSWORD }} \
                ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}
              echo 'Testing image URL using wget...'
              wget -qO - localhost:3000/live | grep live
              wget -qO - --header="Content-Type: application/json" --post-data='{"id":"2"}' localhost:3000/planet | grep -i venus
          - name: Login to GHCR
            uses: docker/login-action@v3.4.0
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}
          - name: Push Image to GHCR
            uses: docker/build-push-action@v4
            with:
              context: .
              push: true
              tags: ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}
    deploy-to-dev:
      if: contains(github.ref, 'feature/')
      needs: [build-push-image]
      name: Deploy to Linode's dev
      uses: ./.github/workflows/deploy.yaml
      with:
        environment: linode_dev
      secrets:
        kubeconfig: ${{ secrets.LINODE_KUBECONFIG }}
        mongodb_password: ${{ secrets.MONGODB_PASSWORD }}
    dev-integration-testing:
      name: dev Integration Testing
      needs: deploy-to-dev
      runs-on: ubuntu-latest
      steps:
        - name: Test URL Output using curl and jq
          env:
            INGRESS_URL: ${{ needs.deploy-to-dev.outputs.ingress_url }}
          run: |
            echo $INGRESS_URL
            echo "-------------------------------------------"
            curl https:/$INGRESS_URL/live -s -k | jq -r .status | grep -i live
    deploy-to-prod:
      if: github.ref == 'refs/heads/main'
      needs: build-push-image
      name: Deploy to prod
      uses: ./.github/workflows/deploy.yaml
      with:
        environment: linode_prod
      secrets:
        kubeconfig: ${{ secrets.LINODE_KUBECONFIG }}
        mongodb_password: ${{ secrets.MONGODB_PASSWORD }}
    prod-integration-testing:
      name: prod Integration Testing
      needs: deploy-to-prod
      runs-on: ubuntu-latest
      steps:
        - name: Test URL Output using curl and jq
          env:
            INGRESS_URL: ${{ needs.deploy-to-prod.outputs.ingress_url }}
          run: |
            echo $INGRESS_URL
            echo "-------------------------------------------"
            curl https:/$INGRESS_URL/live -s -k | jq -r .status | grep -i live